openam_api.settings:
  type: config_object
  label: 'OpenAM API settings'
  mapping:
    debug_response:
      type: boolean
      label: 'Debug Response'
    debug_exception:
      type: boolean
      label: 'Debug Exception'
    openam_api_url:
      type: string
      label: 'OpenAM API Url'
    openam_api_username:
      type: string
      label: 'Your OpenAM Username'
    openam_api_password:
      type: string
      label: 'Your OpenAM Password'
    openam_api_timeout:
      type: integer
      label: 'Maximum allowed time to connect OpenAM server'
    openam_api_operations:
      type: config_object
      label: 'OpenAM API operations settings'
      mapping:
        isValidToken:
          type: mapping
          label: 'Check token validity'
          mapping:
            http_method:
              type: string
              label: 'Http method'
            uri:
              type: string
              label: 'Uri'
            headers:
              type: mapping
              label: 'headers'
              mapping:
                Content-Type:
                  type: string
                  label: 'content type'
                authToken:
                  type: string
                  label: 'authtoken'
        authenticate:
          type: mapping
          label: 'Authenticate'
          mapping:
            http_method:
              type: string
              label: 'Http method'
            uri:
              type: string
              label: 'Uri'
            headers:
              type: mapping
              label: 'headers'
              mapping:
                Content-Type:
                  type: string
                  label: 'content type'
        logout:
          type: mapping
          label: 'Logout'
          mapping:
            http_method:
              type: string
              label: 'Http method'
            uri:
              type: string
              label: 'Uri'
            headers:
              type: mapping
              label: 'headers'
              mapping:
                Content-Type:
                  type: string
                  label: 'content type'
                authToken:
                  type: string
                  label: 'authtoken'
        attributes:
          type: mapping
          label: 'Attributes'
          mapping:
            http_method:
              type: string
              label: 'Http method'
            uri:
              type: string
              label: 'Uri'
            headers:
              type: mapping
              label: 'headers'
              mapping:
                Content-Type:
                  type: string
                  label: 'content type'
                authToken:
                  type: string
                  label: 'authtoken'
