openam_api.settings:
  type: config_object
  label: 'OpenAM API settings'
  mapping:
    debug_response:
      type: boolean
      label: 'Debug Response'
    debug_exception:
      type: boolean
      label: 'Debug Exception'
    openam_api_url:
      type: string
      label: 'OpenAM API Url'
    openam_api_username:
      type: string
      label: 'Your OpenAM Username'
    openam_api_password:
      type: string
      label: 'Your OpenAM Password'
